<a href="https://colab.research.google.com/github/ncbpsicologia/Bootcamp_ITacademy_DataAnalyst/blob/main/Sprint_10_APIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.


1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

- Llista de publicacions (/posts)
- Llista d’usuaris (/users)
- Llista de tasques (/todos)

In [1]:
# Instalamos requests:
!pip install requests

# Importamos dicha libreria:
import requests

# Como en el ejemplo, llamamos a la API:
r = requests.get('https://jsonplaceholder.typicode.com/')

# Verificamos si todo ha salido correctamente:
if r.status_code == 200:
    print("Dades recuperades amb èxit!")

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Dades recuperades amb èxit!

In [2]:
''' Queremos:
Llista de publicacions (/posts)
Llista d’usuaris (/users)
Llista de tasques (/todos)
'''

print("LLISTA DE PUBLICACIONS")
url = "https://jsonplaceholder.typicode.com/posts"
response_posts = requests.get(url)
posts = response_posts.json()
print(posts)

print()

print("LLISTA D'USUARIS")
url = "https://jsonplaceholder.typicode.com/users"
response_users = requests.get(url)
users = response_users.json()
print(users)

print()

print("LLISTA DE TASQUES")
url = "https://jsonplaceholder.typicode.com/todos"
response_todos = requests.get(url)
todos = response_todos.json()
print(todos)

LLISTA DE PUBLICACIONS

2. Mostra per pantalla:

- La quantitat total de cada recurs.
- El codi d'estat de cada petició.

In [3]:
import requests

print("QUANTITAT TOTAL DE CADA RECURS") # lo conseguimos con el método len()

print("Publicacions:", len(posts))
print("Usuaris:", len(users))
print("Tasques:", len(todos))

print()

print("CODI D'ESTAT DE CADA PETICIÓ") # lo conseguimos con .status_code

print("Publicacions:", response_posts.status_code)
print("Usuaris:", response_users.status_code)
print("Tasques:", response_todos.status_code)

# En las 3 sale el código 200, que significa "OK: Todo correcto"

QUANTITAT TOTAL DE CADA RECURS
Publicacions: 100
Usuaris: 10
Tasques: 200

CODI D'ESTAT DE CADA PETICIÓ
Publicacions: 200
Usuaris: 200
Tasques: 200

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [4]:
import requests

print("OBTENIR ERROR 404:") # me invento /animals
url = "https://jsonplaceholder.typicode.com/animals"
response_animals = requests.get(url)
animals = response_animals.json()
print(animals)

print("Animales:", response_animals.status_code)

OBTENIR ERROR 404:
{}
Animales: 404

4. Fes una petició POST per crear una nova publicació fictícia.

Inclou el títol, el cos del missatge i un userId.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [5]:
import requests

print("CREAR NUEVA PUBLICACIÓN")

# indicar donde queremos crear la nueva publicación
url = "https://jsonplaceholder.typicode.com/posts"

# creamos los datos de la publicación
nou_post = {
    "title": "Natàlia practicando",
    "body": "El cuerpo de la publicación fictícia donde explicaría lo que estoy haciendo para aprender.",
    "userId": 1
}

# realizamos el post (enviar datos, a diferenica de antes con el get que los pedíamos)
response_post = requests.post(url, json=nou_post)

# ver la respuesta de la API
print("Resposta JSON:")
print(response_post.json())

print()

# ver el código de estado
print("Codi d'estat:")
print(response_post.status_code)

CREAR NUEVA PUBLICACIÓN
Resposta JSON:
{'title': 'Natàlia practicando', 'body': 'El cuerpo de la publicación fictícia donde explicaría lo que estoy haciendo para aprender.', 'userId': 1, 'id': 101}

Codi d'estat:
201


5. Fes una petició PATCH per modificar parcialment una publicació existent.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [6]:
import requests

print("MODIFICAR MI PUBLICACIÓN")

# indicar donde está la publicación que queremos modificar (añadimos el /1 porque es el id que queremos modificar)
url = "https://jsonplaceholder.typicode.com/posts/1"

# modificamos los datos de la publicación
cambio = {
    "title": "Natàlia aprendiendo",
}

# realizamos el patch ()
response_patch = requests.patch(url, json=cambio)

# ver la respuesta de la API
print("Resposta JSON:")
print(response_patch.json())

print()

# ver el código de estado
print("Codi d'estat:")
print(response_patch.status_code)

MODIFICAR MI PUBLICACIÓN
Resposta JSON:
{'userId': 1, 'id': 1, 'title': 'Natàlia aprendiendo', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

Codi d'estat:
200

6. Fes una petició DELETE sobre una publicació.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [7]:
import requests

print("ELIMINAR PUBLICACIÓn")

# indicamos donde está la publicación que queremos borrar
url = "https://jsonplaceholder.typicode.com/posts/1"

#ejecutamos el delete
response_delete = requests.delete(url)

# ver la respuesta d ela API
print("Resposta JSON:")
print(response_delete.json())

print()

# ver el código de estado
print("Codi d'estat:")
print(response_delete.status_code)

ELIMINAR PUBLICACIÓn
Resposta JSON:
{}

Codi d'estat:
200

# Nivell 2
Interacció amb una API pública real

1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

*`NOTA PREVIA: Como con la primera API que he escogido me ha dado error, he provado otra. Por lo tanto, se puede ir a la celda [30] directamente`*

In [8]:
# Exploro todas las temáticas del repositorio público (https://github.com/public-apis/public-apis) y, por gusto personal, me centro en Anime (https://github.com/public-apis/public-apis#anime)
# De Anime, busco información y veo que Jikan no pide autentificación y acepta HTTP (https://jikan.moe/ )

In [9]:
# Me gustaría seguir mirando Naruto, que es uno de mis animes de la infancia y jamás lo acabé

# Importo la librería
import requests

# Indico el URL
# Esta parte la indica la misma web: https://api.jikan.moe/v4/
# También que el motor de búsqueda es: anime?q=NombreDelAnime
url = "https://api.jikan.moe/v4/anime?q=Naruto"

# Hago la petición GET
response_anime = requests.get(url)

# Muestro la respuesta JSON
print(response_anime.json())

# Muestro el código de estado
print(response_anime.status_code)

# como da un error 504, que indica que no es error del cliente (yo) sinó del servidor, decido cambiar de API

{'status': 504, 'type': 'BadResponseException', 'message': 'Jikan failed to connect to MyAnimeList. MyAnimeList may be down/unavailable or refuses to connect', 'error': None}
504

In [10]:
# cambio a temática musical (https://github.com/public-apis/public-apis#music), opto por MusicBrainz (https://musicbrainz.org/doc/MusicBrainz_API)

'''
La documentación de MusicBrainz dice que para buscar artistas se utiliza:
/ws/2/artist/?query=...

y que podemos pedir la respuesta en JSON añadiendo:
&fmt=json

El espacio se representa con %20

FUENTE: https://musicbrainz.org/doc/MusicBrainz_API/Search?utm_source=chatgpt.com
'''

# Me gustaría buscar información sobre Justin Bieber, artista que seguí mucho en mia dolescencia y sigo escuchando para relajarme

# Importo la librería
import requests

# Indico la URL
url = "https://musicbrainz.org/ws/2/artist/?query=artist:Justin%20Bieber&fmt=json"

# Hago la petición GET
response_music = requests.get(url)

# Muestro la respuesta JSON
print(response_music.json())

# Muestro el código de estado
print(response_music.status_code)

{'created': '2026-09-15T07:19:46.534Z', 'count': 2047, 'offset': 0, 'artists': [{'id': 'e0140a67-e4d1-4f13-8a01-364355bee46e', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 100, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Justin Bieber', 'sort-name': 'Bieber, Justin', 'gender': 'male', 'country': 'CA', 'area': {'id': '71bbafaa-e825-3e15-8ca9-017dcad1748b', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'Canada', 'sort-name': 'Canada', 'life-span': {'ended': None}}, 'begin-area': {'id': 'db3634e7-5414-41dd-be0b-68ae71798dcd', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'London', 'sort-name': 'London', 'life-span': {'ended': None}}, 'ipis': ['00611935265', '00611935363'], 'isnis': ['0000000114791200'], 'life-span': {'begin': '1994-03-01', 'ended': None}, 'aliases': [{'sort-name': '저스틴 비버', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'Justin Bieber', 'locale': 'ko_KR', 'type': 'Artist name', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Justin Beiber', 'type-id': '1937e404-b981-3cb7-8151-4c86ebfc8d8e', 'name': 'Justin Beiber', 'locale': None, 'type': 'Search hint', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'ジャスティン・ビーバー', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'ジャスティン・ビーバー', 'locale': 'ja', 'type': 'Artist name', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Bieber, Justin Drew', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Justin Drew Bieber', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}], 'tags': [{'count': 22, 'name': 'pop'}, {'count': -1, 'name': 'black metal'}, {'count': 0, 'name': 'hip hop'}, {'count': -1, 'name': 'electropop'}, {'count': 2, 'name': 'dance-pop'}, {'count': 1, 'name': 'pop rap'}, {'count': 0, 'name': 'english'}, {'count': 1, 'name': 'reggaeton'}, {'count': -2, 'name': 'gay'}, {'count': -3, 'name': 'amazing'}, {'count': 1, 'name': 'contemporary country'}, {'count': 11, 'name': 'teen pop'}, {'count': -1, 'name': 'christmas music'}, {'count': 1, 'name': 'r&b'}, {'count': 0, 'name': 'contemporary r&b'}, {'count': 3, 'name': '2010s'}, {'count': 1, 'name': 'tropical house'}, {'count': 0, 'name': 'terrible'}, {'count': 0, 'name': 'awful'}, {'count': 2, 'name': '2020s'}, {'count': 0, 'name': 'reggea'}]}, {'id': 'a9cb6a8f-cc7b-48d6-bd10-2a4afeba600e', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 78, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Bieber', 'sort-name': 'Bieber', 'gender': 'male', 'life-span': {'ended': None}, 'aliases': [{'sort-name': 'The Bieber', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'The Bieber', 'locale': None, 'type': 'Artist name', 'primary': None, 'begin-date': None, 'end-date': None}]}, {'id': 'c7d0d6f4-4eb2-4d36-8f61-fe7e2ce4af0d', 'score': 76, 'name': 'Justin Bieber Nickelback', 'sort-name': 'Justin Bieber Nickelback', 'life-span': {'ended': None}}, {'id': '6140b24a-816f-4f99-a2b7-d2346d6e5cc9', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 69, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Andreas Bieber', 'sort-name': 'Bieber, Andreas', 'gender': 'male', 'life-span': {'ended': None}}, {'id': '92a02b9c-e54d-4e93-a70b-7672d370e5ab', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 69, 'gender-id': '93452b5a-a947-30c8-934f-6a4056b151c2', 'name': 'Heidi Bieber', 'sort-name': 'Bieber, Heidi', 'gender': 'female', 'country': 'DE', 'area': {'id': '85752fda-13c4-31a3-bee5-0e5cb1f51dad', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'Germany', 'sort-name': 'Germany', 'life-span': {'ended': None}}, 'begin-area': {'id': 'a57848d1-b1ae-41e1-8ebc-949f4ea986fe', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Marburg', 'sort-name': 'Marburg', 'life-span': {'ended': None}}, 'life-span': {'ended': None}}, {'id': 'f820d106-f98c-4226-94bf-42195bff9507', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Clemens Bieber', 'sort-name': 'Bieber, Clemens', 'gender': 'male', 'begin-area': {'id': 'f0463abf-0d3b-4be7-bb68-145e65311193', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Würzburg', 'sort-name': 'Würzburg', 'life-span': {'ended': None}}, 'disambiguation': 'german operatic tenor', 'isnis': ['0000000114516014'], 'life-span': {'begin': '1956-01-26', 'ended': None}}, {'id': '237dbe62-72c2-44a2-8ba5-ea63fadba9fa', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Keith Bieber', 'sort-name': 'Bieber, Keith', 'gender': 'male', 'life-span': {'ended': None}}, {'id': '1fcd2e9b-7397-437f-98d3-4f685b74bedd', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Jeremy Bieber', 'sort-name': 'Bieber, Jeremy', 'gender': 'male', 'country': 'CA', 'area': {'id': '71bbafaa-e825-3e15-8ca9-017dcad1748b', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'Canada', 'sort-name': 'Canada', 'life-span': {'ended': None}}, 'disambiguation': 'Justin’s father', 'life-span': {'ended': None}, 'aliases': [{'sort-name': 'Bieber, Jeremy Jack', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Jeremy Jack Bieber', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}]}, {'id': '4e151144-57f2-4acb-b3b8-3e089b106d25', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Martin Bieber', 'sort-name': 'Bieber, Martin', 'gender': 'male', 'disambiguation': 'violinist and mandolinist', 'life-span': {'begin': '1956', 'ended': None}}, {'id': '9c60b68c-d099-4c8d-9a0f-fd2c6788c72f', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Shachar Bieber', 'sort-name': 'Bieber, Shachar', 'gender': 'male', 'disambiguation': 'singer & bass player', 'life-span': {'ended': None}}, {'id': '349430f6-8e55-4bcc-b889-f935c5b57264', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '93452b5a-a947-30c8-934f-6a4056b151c2', 'name': 'Hailey Bieber', 'sort-name': 'Bieber, Hailey', 'gender': 'female', 'begin-area': {'id': '7c71f821-98a0-4f1b-bf6b-87fe1d6c89f0', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Tucson', 'sort-name': 'Tucson', 'life-span': {'ended': None}}, 'life-span': {'begin': '1996-11-22', 'ended': None}}, {'id': '8ac5cc36-896a-4c96-8250-a15cd670a6f1', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Boyz Bieber', 'sort-name': 'Bieber, Boyz', 'gender': 'male', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'life-span': {'ended': None}, 'aliases': [{'sort-name': 'Bieber, Jossi Gandhi', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Jossi Gandhi Bieber', 'locale': 'en', 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}]}, {'id': 'cf66fbfb-b312-4f41-9880-764971cdc8dd', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '93452b5a-a947-30c8-934f-6a4056b151c2', 'name': 'Emily Bieber', 'sort-name': 'Bieber, Emily', 'gender': 'female', 'life-span': {'ended': None}}, {'id': '3c02dfff-2f5a-4592-8883-43d2a4ed65a0', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Reinhold Bieber', 'sort-name': 'Bieber, Reinhold', 'gender': 'male', 'disambiguation': "trumpet player and trombonist; member of Da Blechhauf'n", 'life-span': {'ended': None}}, {'id': 'c9dd6f52-541f-4ed8-a006-394902284723', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Gavin Bieber', 'sort-name': 'Bieber, Gavin', 'gender': 'male', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'ipis': ['00247181468'], 'life-span': {'ended': None}, 'aliases': [{'sort-name': 'Bieber, Gavin Jon', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Gavin Jon Bieber', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}]}, {'id': '8ed9e118-f2eb-400e-9dd5-b4869194e3e0', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'name': 'Patrick Bieber', 'sort-name': 'Bieber, Patrick', 'life-span': {'ended': None}}, {'id': '9371fa2a-b452-4d75-957e-0749fb2ae1f4', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '93452b5a-a947-30c8-934f-6a4056b151c2', 'name': 'Stefanie Bieber', 'sort-name': 'Bieber, Stefanie', 'gender': 'female', 'life-span': {'ended': None}}, {'id': '4f4ed096-af56-4c61-919b-f0822de880e7', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Brian Bieber', 'sort-name': 'Bieber, Brian', 'gender': 'male', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'isnis': ['0000000407122780'], 'life-span': {'ended': None}}, {'id': 'f2edaa7d-d13d-44aa-9463-5f64a5932fa7', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 68, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Nathan Bieber', 'sort-name': 'Bieber, Nathan', 'gender': 'male', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'life-span': {'ended': None}}, {'id': '5ddd8788-a3c7-485a-bbee-e83a408a4a25', 'score': 68, 'name': 'Katy Bieber', 'sort-name': 'Bieber, Katy', 'disambiguation': 'chillout', 'life-span': {'ended': None}}, {'id': 'df47ea9a-b54e-440f-86bb-4c16bc33f6f2', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 62, 'gender-id': '93452b5a-a947-30c8-934f-6a4056b151c2', 'name': 'Angela-Charlott Bieber', 'sort-name': 'Bieber, Angela-Charlott', 'gender': 'female', 'life-span': {'ended': None}}, {'id': '596ffa74-3d08-44ef-b113-765d43d12738', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 60, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Justin Timberlake', 'sort-name': 'Timberlake, Justin', 'gender': 'male', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'begin-area': {'id': 'c2d96f61-75a4-4375-aed5-6aacb0b6326a', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Memphis', 'sort-name': 'Memphis', 'life-span': {'ended': None}}, 'ipis': ['00345256954'], 'isnis': ['000000011450569X'], 'life-span': {'begin': '1981-01-31', 'ended': None}, 'aliases': [{'sort-name': 'Justin Timberlake', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'ジャスティン・ティンバーレイク', 'locale': 'ja', 'type': 'Artist name', 'primary': True, 'begin-date': None, 'end-date': None}, {'sort-name': 'Timberlake, Justin Randall', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Justin Randall Timberlake', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Justine Timberlake', 'name': 'Justine Timberlake', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Justin "TENNMAN" Timberlake', 'name': 'Justin "TENNMAN" Timberlake', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Trousersnake', 'name': 'Trousersnake', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'J. Timberlake', 'name': 'J. Timberlake', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Timberlake, Justin R.', 'name': 'Justin R. Timberlake', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}], 'tags': [{'count': 7, 'name': 'pop'}, {'count': 1, 'name': 'dance'}, {'count': 1, 'name': 'hip hop'}, {'count': 1, 'name': 'electropop'}, {'count': 3, 'name': 'disco'}, {'count': 1, 'name': '2000s'}, {'count': 4, 'name': 'dance-pop'}, {'count': 1, 'name': 'boogie'}, {'count': 1, 'name': 'neo soul'}, {'count': 1, 'name': 'latin'}, {'count': 0, 'name': 'pop and chart'}, {'count': 1, 'name': 'teen pop'}, {'count': 4, 'name': 'r&b'}, {'count': 3, 'name': 'contemporary r&b'}, {'count': 1, 'name': 'synth funk'}]}, {'id': '183aca94-579b-4dbb-82b0-c0e066b61019', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 52, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Justin Richards', 'sort-name': 'Richards, Justin', 'gender': 'male', 'country': 'GB', 'area': {'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United Kingdom', 'sort-name': 'United Kingdom', 'life-span': {'ended': None}}, 'begin-area': {'id': 'b084c8bc-bab4-4b29-84f6-f7acec85e7c2', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Epping', 'sort-name': 'Epping', 'life-span': {'ended': None}}, 'disambiguation': 'British writer', 'life-span': {'begin': '1961-09-14', 'ended': None}}, {'id': '6064ca35-64d5-4a48-8575-5f17cd0f200c', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 51, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Simon Fava', 'sort-name': 'Fava, Simon', 'gender': 'male', 'country': 'DE', 'area': {'id': '85752fda-13c4-31a3-bee5-0e5cb1f51dad', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'Germany', 'sort-name': 'Germany', 'life-span': {'ended': None}}, 'disambiguation': 'Simon Bieber', 'life-span': {'ended': None}}, {'id': 'c113d7a7-2b22-49dc-886b-366ee68577cb', 'type': 'Person', 'type-id': 'b6e035f4-3ce9-331c-97df-83397230b0df', 'score': 51, 'gender-id': '36d3d30a-839d-3eda-8cb3-29be4384e4a9', 'name': 'Justin Hayward', 'sort-name': 'Hayward, Justin', 'gender': 'male', 'country': 'GB', 'area': {'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United Kingdom', 'sort-name': 'United Kingdom', 'life-span': {'ended': None}}, 'begin-area': {'id': 'aee482fe-df6b-4f0f-849f-18f2329bab7c', 'type': 'Subdivision', 'type-id': 'fd3d44c5-80a1-3842-9745-2c4972d35afa', 'name': 'Swindon', 'sort-name': 'Swindon', 'life-span': {'ended': None}}, 'disambiguation': 'of the Moody Blues', 'ipis': ['00087076940'], 'isnis': ['0000000063044415'], 'life-span': {'begin': '1946-10-14', 'ended': None}, 'aliases': [{'sort-name': 'Hayward, Justin David', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Justin David Hayward', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Haywood, Justin', 'name': 'Justin Haywood', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Justin Heyward', 'name': 'Justin Heyward', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}], 'tags': [{'count': 2, 'name': 'rock'}, {'count': 1, 'name': 'rock and indie'}, {'count': 1, 'name': 'prog rock'}]}]}
200

2. Llegeix la documentació de l'API:

- Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
- Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
- Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

Documentación de la API MusicBrainz

**ENDPOINTS**

Dos de los endpoints disponibles son:

- `/ws/2/artist` → buscar info sobre artistas (como he hecho en el ejemplo)
- `/ws/2/recording` → buscar info sobre canciones



**PARÁMETROS Y FILTROS**

Esta API pemite utilizar estos parámetros en las búsquedas:

- `query` → indica qu queremos buscar
- `limit` → indica el nº max. de resultados que queremos obtener (entre 1 y 100)
- `offset` → permite empezar los resultados desde una posición
- `fmt` → permite escoger el formato de respuesta (indicando por ejemplo `json`como he hehco en el ejemplo de JB)

En les cerques d'artistes també podem utilitzar camps com `artist`, `country`, `type`, `gender`, `area` o `tag` per filtrar els resultats.



**FORMATO DE RESPUESTA**

Podemos obtener el formato json usando el paràmetre `fmt=json`.
Se comprueba usando, en este caso, `response_music.json()`

3. Fes una petició GET senzilla:

- Mostra el codi d'estat de la resposta.
- Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [11]:
# Voy a pedir información sobre Justin Bieber

print("INFORMACIÓN DE JUSTIN BIEBER")

url = "https://musicbrainz.org/ws/2/artist/?query=artist:Justin%20Bieber&fmt=json"

response_music = requests.get(url)
music = response_music.json()

# Código de estado
print("Codi d'estat:", response_music.status_code)

# Algunos campos de la respuesta JSON
print("Nombre de resultados:", music["count"])
print("Primer artista encontrado:", music["artists"][0]["name"])

INFORMACIÓN DE JUSTIN BIEBER
Codi d'estat: 200
Nombre de resultados: 2047
Primer artista encontrado: Justin Bieber

4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [12]:
# Importo pandas
import pandas as pd

# Convierto los artistas dentro de music a un DataFrame
df_artistasJB = pd.DataFrame(music["artists"])

# Muestro las primeras filas
df_artistasJB.head()

,id,type,type-id,score,gender-id,name,sort-name,gender,country,area,begin-area,ipis,isnis,life-span,aliases,tags,disambiguation
0,e0140a67-e4d1-4f13-8a01-364355bee46e,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Justin Bieber,"Bieber, Justin",male,CA,"{'id': '71bbafaa-e825-3e15-8ca9-017dcad1748b',...","{'id': 'db3634e7-5414-41dd-be0b-68ae71798dcd',...","[00611935265, 00611935363]",[0000000114791200],"{'begin': '1994-03-01', 'ended': None}","[{'sort-name': '저스틴 비버', 'type-id': '894afba6-...","[{'count': 22, 'name': 'pop'}, {'count': -1, '...",NaN
1,a9cb6a8f-cc7b-48d6-bd10-2a4afeba600e,Person,b6e035f4-3ce9-331c-97df-83397230b0df,78,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Bieber,Bieber,male,NaN,NaN,NaN,NaN,NaN,{'ended': None},"[{'sort-name': 'The Bieber', 'type-id': '894af...",NaN,NaN
2,c7d0d6f4-4eb2-4d36-8f61-fe7e2ce4af0d,NaN,NaN,76,NaN,Justin Bieber Nickelback,Justin Bieber Nickelback,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN,NaN
3,6140b24a-816f-4f99-a2b7-d2346d6e5cc9,Person,b6e035f4-3ce9-331c-97df-83397230b0df,69,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Andreas Bieber,"Bieber, Andreas",male,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN,NaN
4,92a02b9c-e54d-4e93-a70b-7672d370e5ab,Person,b6e035f4-3ce9-331c-97df-83397230b0df,69,93452b5a-a947-30c8-934f-6a4056b151c2,Heidi Bieber,"Bieber, Heidi",female,DE,"{'id': '85752fda-13c4-31a3-bee5-0e5cb1f51dad',...","{'id': 'a57848d1-b1ae-41e1-8ebc-949f4ea986fe',...",NaN,NaN,{'ended': None},NaN,NaN,NaN

# Nivell 3
API d'Open Data Barcelona

1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [13]:
# Importo la librería
import requests

# URL del endpoint package_search
url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search"

'''
Lo usamos para encontrar conjuntos de datos que coinciden con una consulta (mediante q=text po rejemplo) y retorna lista en formato json
'''

# con q indicamos que queremos buscar (accidentes)
params = {"q": "accidents"}

# petición a la IA
response_accidents = requests.get(url, params=params)

# convertir respuesta a json (tipo diccionario de python)
data = response_accidents.json()

data

# en 'count': 6 vemos que ha encontrado 6 dfs

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_search',
 'success': True,
 'result': {'count': 6,
  'sort': 'fecha_publicacion desc',
  'facets': {},
  'results': [{'notes_translated': {'ca': 'Accidents segons causa conductor  gestionats per la Guàrdia Urbana a la ciutat de Barcelona  ',
     'en': 'Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona',
     'es': 'Accidentes  según causa conductor gestionados por la Guàrdia Urbana a la ciutat de Barcelona'},
    'geolocation': 'Yes_with_map_view',
    'dades_alt_valor': 'No',
    'url_tornada': {'ca': 'http://ajuntament.barcelona.cat/guardiaurbana/ca',
     'en': 'http://ajuntament.barcelona.cat/guardiaurbana/en',
     'es': 'http://ajuntament.barcelona.cat/guardiaurbana/es'},
    'dataset_fields_description': "Les dades d’aquest dataset complementen les d'[Accidents gestionats per la Guàrdia Urbana a la ciutat de Barcelona](http://opendata-ajuntament.barcelona.cat/data/ca/dataset?name=accidents-gu-bcn)    \r\nEl valor '-1' en una cel·la indica que no es disposa de la dada.",
    'fuente': 'Ajuntament de Barcelona',
    'tag': 'Accidentalitat,Guàrdia Urbana,Causa conductor,Any 2016,Any 2017,Any 2018,Any 2019,Any 2020,Any 2021,Any 2022,Any 2023,Any 2024,Any 2025',
    'private': False,
    'num_tags': 13,
    'code': 'ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN',
    'frequency': 'ANUAL',
    'id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'title_translated': {'ca': 'Accidents segons causa conductor  gestionats per la Guàrdia Urbana a la ciutat de Barcelona  ',
     'en': 'Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona',
     'es': 'Accidentes  según causa conductor gestionados por la Guàrdia Urbana a la ciutat de Barcelona'},
    'metadata_modified': '2026-04-28T06:55:23.287658',
    'author': 'Gerència d’Àrea de Seguretat, Prevenció i Convivència',
    'author_email': None,
    'isopen': True,
    'long_format': 'No',
    'state': 'active',
    'version': '',
    'mar_od': 'Yes',
    'relationships_as_object': [],
    'department': "Sistemes d'Informació i Telecomunicacions",
    'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf',
    'type': 'dataset',
    'resources': [{'api_access_number_absolute': '3202',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '796504f6-7602-41a7-82a9-d3bd47e68dee',
      'description': '',
      'state': 'active',
      'api_access_number': '624',
      'size': '1439045',
      'token_required': 'No',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '173',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2025_accidents_causa_conductor_gu_bcn.csv',
      'created': '2026-02-12T20:24:24.846383',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/796504f6-7602-41a7-82a9-d3bd47e68dee/download',
      'downloads_absolute': '228',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.792748\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-02-13T02:05:10.424560\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2026-02-17T11:27:25.876654',
      'position': 0,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'api_access_number_absolute': '509',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '8cfddcbe-3403-4a6c-8897-c13238da900e',
      'description': '',
      'state': 'active',
      'api_access_number': '296',
      'size': '1397262',
      'token_required': 'No',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '426',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2024_accidents_causa_conductor_gu_bcn.csv',
      'created': '2025-02-05T17:02:05.373273',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/8cfddcbe-3403-4a6c-8897-c13238da900e/download',
      'downloads_absolute': '754',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.803372\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-02-06T02:04:37.224147\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2025-02-05T17:02:05.264993',
      'position': 1,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '5a040155-38b3-4b19-a4b0-c84a0618d363',
      'size': '1962577',
      'state': 'active',
      'api_access_number': '345',
      'api_access_number_absolute': '663',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '772',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2023_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2024-02-08T09:30:32.142096',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/5a040155-38b3-4b19-a4b0-c84a0618d363/download',
      'downloads_absolute': '1390',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.813696\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-02-09T02:04:01.473637\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2024-02-08T09:30:32.036701',
      'position': 2,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '87a8aeda-d3eb-4ba5-bcad-b9ab0c296df5',
      'size': '2211402',
      'state': 'active',
      'api_access_number': '736',
      'api_access_number_absolute': '1954',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '1480',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2022_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-14T07:05:39.930459',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/87a8aeda-d3eb-4ba5-bcad-b9ab0c296df5/download',
      'downloads_absolute': '2233',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.829915\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-15T02:03:18.372056\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-04-13T16:20:35.974576',
      'position': 3,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': 'b384d295-5aec-49b1-86de-c3096ee39209',
      'size': '1972965',
      'state': 'active',
      'api_access_number': '240',
      'api_access_number_absolute': '286',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '1010',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2021_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-13T12:54:26.226996',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/b384d295-5aec-49b1-86de-c3096ee39209/download',
      'downloads_absolute': '1222',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.839894\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-14T02:04:56.763862\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-02-13T12:54:26.181028',
      'position': 4,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': 'ab22b7f9-a780-4c8b-8605-eb0e35b4094c',
      'size': '1742396',
      'state': 'active',
      'api_access_number': '198',
      'api_access_number_absolute': '236',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '676',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2020_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-14T07:06:42.311752',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/ab22b7f9-a780-4c8b-8605-eb0e35b4094c/download',
      'downloads_absolute': '824',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.858031\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-15T02:03:18.392468\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-02-14T07:06:42.106609',
      'position': 5,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '240bbe6f-b01e-4c7c-8f5f-69ce317a1d01',
      'size': '2522304',
      'state': 'active',
      'api_access_number': '313',
      'api_access_number_absolute': '350',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '853',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2019_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-14T07:07:42.492653',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/240bbe6f-b01e-4c7c-8f5f-69ce317a1d01/download',
      'downloads_absolute': '1006',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.872812\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-15T02:03:18.401624\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-02-14T07:07:42.280760',
      'position': 6,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '3d856a5d-30e8-494c-8390-c039e5c8919b',
      'size': '2485179',
      'state': 'active',
      'api_access_number': '259',
      'api_access_number_absolute': '294',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '887',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2018_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-14T07:04:44.218424',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/3d856a5d-30e8-494c-8390-c039e5c8919b/download',
      'downloads_absolute': '1017',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.896871\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-15T02:03:18.411246\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-02-14T07:04:44.100691',
      'position': 7,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': '1a05cdd4-4844-41a5-872d-a0824d11b517',
      'size': '2533893',
      'state': 'active',
      'api_access_number': '836',
      'api_access_number_absolute': '1786',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '843',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2017_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-14T07:03:58.586744',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/1a05cdd4-4844-41a5-872d-a0824d11b517/download',
      'downloads_absolute': '1012',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.908806\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-15T02:03:18.423369\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-02-14T07:03:58.463706',
      'position': 8,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
      'datastore_active': True,
      'id': 'f464ffc3-b6c0-4bce-9749-a8ed53bcc9fa',
      'size': '2397973',
      'state': 'active',
      'api_access_number': '255',
      'api_access_number_absolute': '291',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '869',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2016_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
      'created': '2023-02-14T07:03:09.825725',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/f464ffc3-b6c0-4bce-9749-a8ed53bcc9fa/download',
      'downloads_absolute': '1015',
      'map_visualization_res': 'data_explorer_map',
      'qa': '{\'updated\': \'2026-09-15T02:05:10.919085\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2023-02-15T02:03:18.434044\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2023-02-14T07:03:09.746657',
      'position': 9,
      'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
      'resource_type': None}],
    'token_required': 'No',
    'decalatgeNum': '1',
    'tags': [{'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Accidentalitat',
      'id': '1d0c1531-1434-477b-96ef-41c50382c0fd',
      'name': 'Accidentalitat'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2016',
      'id': 'bf305973-29e7-4ae1-b821-ee6bdb1d9748',
      'name': 'Any 2016'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2017',
      'id': '1fde7902-49a3-45b0-be19-a19872d01398',
      'name': 'Any 2017'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2018',
      'id': '6a090c69-7263-425a-a2ef-41f5f2f93ca0',
      'name': 'Any 2018'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2019',
      'id': '4fdbddac-00a9-480e-a846-8148522b3500',
      'name': 'Any 2019'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2020',
      'id': '2ff883a0-d01a-4af3-8235-8407a6e411a7',
      'name': 'Any 2020'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2021',
      'id': '28ab7cce-e938-4cca-adc6-800b03070775',
      'name': 'Any 2021'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2022',
      'id': '224016e4-81b8-4e60-819b-e7119ced7589',
      'name': 'Any 2022'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2023',
      'id': '3f5176c6-4773-426d-b3f4-729d7d47f59d',
      'name': 'Any 2023'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2024',
      'id': '283fc2f8-cbae-4ef0-9884-edf991193b9f',
      'name': 'Any 2024'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2025',
      'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
      'name': 'Any 2025'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Causa conductor',
      'id': '820e2e49-db27-49a2-8779-67decd9a054c',
      'name': 'Causa conductor'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Guàrdia Urbana',
      'id': '5290a3c8-1cd7-44e0-9db1-87dc588c3e4f',
      'name': 'Guàrdia Urbana'}],
    'ODS_Principal_agenda_2030': 'ODS 3: Salut i benestar',
    'fecha_publicacion': '2023-02-14',
    'ODS_Colateral2_agenda_2030': 'N/A',
    'ODS_Colateral1_agenda_2030': 'N/A',
    'license_id': 'CC-BY-4.0',
    'hide_url': 'No',
    'relationships_as_subject': [],

In [29]:
# Importo la librería
import requests

url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show"

'''
Para obtener toda la info y metadatos completos de un conjunto de datos concreto del cual conocemos el id (el que uso en este caso) o el nombre
'''

# escogemos el primero, que contiene accidentes gestionados por la guardia urbana
params = {"id": "29d1b774-a83e-4c1e-91f7-1b9ad042ea83"}

response_acc = requests.get(url, params=params)

data1 = response_acc.json()

data1

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'notes_translated': {'ca': 'Accidents segons causa conductor  gestionats per la Guàrdia Urbana a la ciutat de Barcelona  ',
   'en': 'Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona',
   'es': 'Accidentes  según causa conductor gestionados por la Guàrdia Urbana a la ciutat de Barcelona'},
  'geolocation': 'Yes_with_map_view',
  'dades_alt_valor': 'No',
  'url_tornada': {'ca': 'http://ajuntament.barcelona.cat/guardiaurbana/ca',
   'en': 'http://ajuntament.barcelona.cat/guardiaurbana/en',
   'es': 'http://ajuntament.barcelona.cat/guardiaurbana/es'},
  'dataset_fields_description': "Les dades d’aquest dataset complementen les d'[Accidents gestionats per la Guàrdia Urbana a la ciutat de Barcelona](http://opendata-ajuntament.barcelona.cat/data/ca/dataset?name=accidents-gu-bcn)    \r\nEl valor '-1' en una cel·la indica que no es disposa de la dada.",
  'fuente': 'Ajuntament de Barcelona',
  'tag': 'Accidentalitat,Guàrdia Urbana,Causa conductor,Any 2016,Any 2017,Any 2018,Any 2019,Any 2020,Any 2021,Any 2022,Any 2023,Any 2024,Any 2025',
  'private': False,
  'num_tags': 13,
  'code': 'ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN',
  'frequency': 'ANUAL',
  'id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
  'title_translated': {'ca': 'Accidents segons causa conductor  gestionats per la Guàrdia Urbana a la ciutat de Barcelona  ',
   'en': 'Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona',
   'es': 'Accidentes  según causa conductor gestionados por la Guàrdia Urbana a la ciutat de Barcelona'},
  'metadata_modified': '2026-04-28T06:55:23.287658',
  'author': 'Gerència d’Àrea de Seguretat, Prevenció i Convivència',
  'author_email': None,
  'isopen': True,
  'long_format': 'No',
  'state': 'active',
  'version': '',
  'mar_od': 'Yes',
  'relationships_as_object': [],
  'department': "Sistemes d'Informació i Telecomunicacions",
  'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf',
  'type': 'dataset',
  'resources': [{'api_access_number_absolute': 3202,
    'cache_last_updated': None,
    'incorporated_in_cityos_res': 'No',
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '796504f6-7602-41a7-82a9-d3bd47e68dee',
    'description': '',
    'state': 'active',
    'api_access_number': 624,
    'size': '1439045',
    'token_required': 'No',
    'hash': '',
    'token_name': '',
    'format': 'CSV',
    'downloads': 173,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'column_types': '',
    'hide_url': 'No',
    'token_version': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2025_accidents_causa_conductor_gu_bcn.csv',
    'created': '2026-02-12T20:24:24.846383',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/796504f6-7602-41a7-82a9-d3bd47e68dee/download/2025_accidents_causa_conductor_gu_bcn.csv',
    'downloads_absolute': 228,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.792748',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2026-02-13T02:05:10.424560',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2026-02-17T11:27:25.876654',
    'position': 0,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'api_access_number_absolute': 509,
    'cache_last_updated': None,
    'incorporated_in_cityos_res': 'No',
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '8cfddcbe-3403-4a6c-8897-c13238da900e',
    'description': '',
    'state': 'active',
    'api_access_number': 296,
    'size': '1397262',
    'token_required': 'No',
    'hash': '',
    'token_name': '',
    'format': 'CSV',
    'downloads': 426,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'column_types': '',
    'hide_url': 'No',
    'token_version': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_accidents_causa_conductor_gu_bcn.csv',
    'created': '2025-02-05T17:02:05.373273',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/8cfddcbe-3403-4a6c-8897-c13238da900e/download/2024_accidents_causa_conductor_gu_bcn.csv',
    'downloads_absolute': 754,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.803372',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-02-06T02:04:37.224147',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2025-02-05T17:02:05.264993',
    'position': 1,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '5a040155-38b3-4b19-a4b0-c84a0618d363',
    'size': '1962577',
    'state': 'active',
    'api_access_number': 345,
    'api_access_number_absolute': 663,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 772,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'column_types': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2024-02-08T09:30:32.142096',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/5a040155-38b3-4b19-a4b0-c84a0618d363/download/2023_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 1390,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.813696',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2024-02-09T02:04:01.473637',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2024-02-08T09:30:32.036701',
    'position': 2,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '87a8aeda-d3eb-4ba5-bcad-b9ab0c296df5',
    'size': '2211402',
    'state': 'active',
    'api_access_number': 736,
    'api_access_number_absolute': 1954,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 1480,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'column_types': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-14T07:05:39.930459',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/87a8aeda-d3eb-4ba5-bcad-b9ab0c296df5/download/2022_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 2233,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.829915',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-15T02:03:18.372056',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-04-13T16:20:35.974576',
    'position': 3,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': 'b384d295-5aec-49b1-86de-c3096ee39209',
    'size': '1972965',
    'state': 'active',
    'api_access_number': 240,
    'api_access_number_absolute': 286,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 1010,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-13T12:54:26.226996',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/b384d295-5aec-49b1-86de-c3096ee39209/download/2021_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 1222,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.839894',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-14T02:04:56.763862',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-02-13T12:54:26.181028',
    'position': 4,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': 'ab22b7f9-a780-4c8b-8605-eb0e35b4094c',
    'size': '1742396',
    'state': 'active',
    'api_access_number': 198,
    'api_access_number_absolute': 236,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 676,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-14T07:06:42.311752',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/ab22b7f9-a780-4c8b-8605-eb0e35b4094c/download/2020_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 824,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.858031',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-15T02:03:18.392468',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-02-14T07:06:42.106609',
    'position': 5,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '240bbe6f-b01e-4c7c-8f5f-69ce317a1d01',
    'size': '2522304',
    'state': 'active',
    'api_access_number': 313,
    'api_access_number_absolute': 350,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 853,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2019_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-14T07:07:42.492653',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/240bbe6f-b01e-4c7c-8f5f-69ce317a1d01/download/2019_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 1006,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.872812',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-15T02:03:18.401624',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-02-14T07:07:42.280760',
    'position': 6,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '3d856a5d-30e8-494c-8390-c039e5c8919b',
    'size': '2485179',
    'state': 'active',
    'api_access_number': 259,
    'api_access_number_absolute': 294,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 887,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2018_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-14T07:04:44.218424',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/3d856a5d-30e8-494c-8390-c039e5c8919b/download/2018_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 1017,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.896871',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-15T02:03:18.411246',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-02-14T07:04:44.100691',
    'position': 7,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': '1a05cdd4-4844-41a5-872d-a0824d11b517',
    'size': '2533893',
    'state': 'active',
    'api_access_number': 836,
    'api_access_number_absolute': 1786,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 843,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2017_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-14T07:03:58.586744',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/1a05cdd4-4844-41a5-872d-a0824d11b517/download/2017_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 1012,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.908806',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-15T02:03:18.423369',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-02-14T07:03:58.463706',
    'position': 8,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '29d1b774-a83e-4c1e-91f7-1b9ad042ea83',
    'datastore_active': True,
    'id': 'f464ffc3-b6c0-4bce-9749-a8ed53bcc9fa',
    'size': '2397973',
    'state': 'active',
    'api_access_number': 255,
    'api_access_number_absolute': 291,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 869,
    'mimetype_inner': None,
    'url_type': 'upload',
    'token_provider': '',
    'mimetype': None,
    'cache_url': None,
    'name': '2016_ACCIDENTS_CAUSA_CONDUCTOR_GU_BCN_.csv',
    'created': '2023-02-14T07:03:09.825725',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/29d1b774-a83e-4c1e-91f7-1b9ad042ea83/resource/f464ffc3-b6c0-4bce-9749-a8ed53bcc9fa/download/2016_accidents_causa_conductor_gu_bcn_.csv',
    'downloads_absolute': 1015,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-09-15T02:05:10.919085',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2023-02-15T02:03:18.434044',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2023-02-14T07:03:09.746657',
    'position': 9,
    'revision_id': 'f196f4cc-fa92-4018-b522-79ad4e87121b',
    'resource_type': None}],
  'token_required': 'No',
  'decalatgeNum': '1',
  'tags': [{'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Accidentalitat',
    'id': '1d0c1531-1434-477b-96ef-41c50382c0fd',
    'name': 'Accidentalitat'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2016',
    'id': 'bf305973-29e7-4ae1-b821-ee6bdb1d9748',
    'name': 'Any 2016'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2017',
    'id': '1fde7902-49a3-45b0-be19-a19872d01398',
    'name': 'Any 2017'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2018',
    'id': '6a090c69-7263-425a-a2ef-41f5f2f93ca0',
    'name': 'Any 2018'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2019',
    'id': '4fdbddac-00a9-480e-a846-8148522b3500',
    'name': 'Any 2019'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2020',
    'id': '2ff883a0-d01a-4af3-8235-8407a6e411a7',
    'name': 'Any 2020'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2021',
    'id': '28ab7cce-e938-4cca-adc6-800b03070775',
    'name': 'Any 2021'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2022',
    'id': '224016e4-81b8-4e60-819b-e7119ced7589',
    'name': 'Any 2022'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2023',
    'id': '3f5176c6-4773-426d-b3f4-729d7d47f59d',
    'name': 'Any 2023'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2024',
    'id': '283fc2f8-cbae-4ef0-9884-edf991193b9f',
    'name': 'Any 2024'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Any 2025',
    'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
    'name': 'Any 2025'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Causa conductor',
    'id': '820e2e49-db27-49a2-8779-67decd9a054c',
    'name': 'Causa conductor'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Guàrdia Urbana',
    'id': '5290a3c8-1cd7-44e0-9db1-87dc588c3e4f',
    'name': 'Guàrdia Urbana'}],
  'ODS_Principal_agenda_2030': 'ODS 3: Salut i benestar',
  'fecha_publicacion': '2023-02-14',
  'ODS_Colateral2_agenda_2030': 'N/A',
  'ODS_Colateral1_agenda_2030': 'N/A',
  'license_id': 'CC-BY-4.0',
  'hide_url': 'No',
  'relationships_as_subject': [],
  'license_title': 'Creative Commons Attribution 4.0',
  'groups': [],
  'num_resources': 10,
  'organization': {'description': '',
   'created': '2017-01-24T16:55:05.721859',
   'title': 'Seguretat',
   'name': 'seguretat',
   'is_organization': True,
   'state': 'active',
   'image_url': 'bcn-icon-prevencio-seguretat',
   'revision_id': 'e8a09edc-0441-4aa3-8b9e-02533fc824f2',
   'type': 'organization',
   'id': '258c7572-02b4-492e-a692-353e297fe320',
   'approval_status': 'approved'},

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [30]:
# Importo la librería
import requests

# De la info guardada en data1, entramos en la clave result, buscamos resources, nos quedamos con el primer recurso ([0]) y pedimos su format.

print('comprobar formato:')
data1['result']['resources'][0]['format']

comprobar formato:

'CSV'

In [31]:
# Importo la librería
import requests

# como si es CSV, busco su nombre para mejor legibilidad:
print('nombre del recurso:')
data1['result']['resources'][0]['name']

nombre del recurso:

'2025_accidents_causa_conductor_gu_bcn.csv'

3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [32]:
# Importo la librería
import requests

# como pide el resource_id, en vez de manualmente, lo busco igual que antes:

print('id del recurso:')
data1['result']['resources'][0]['id']

id del recurso:

'796504f6-7602-41a7-82a9-d3bd47e68dee'

In [37]:
# Importo la librería
import requests

url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search"

params = {
    "resource_id": data1['result']['resources'][0]['id']
}

response_id = requests.get(url, params=params)

data2 = response_id.json()

In [38]:
#para recuperar 100 filas, veo que hay dos maneras de hacerlo:
# 1, convirtiendo a df para usar los métodos aprendidos en sprints anteriores (como sample o head)

import pandas as pd

df = pd.DataFrame(data2['result']['records'])

df.sample(100)

,Codi_districte,Coordenada_UTM_X_ED50,Nk_Any,Causa conductor,Nom_districte,Descripcio_torn,Coordenada_UTM_Y_ED50,Codi_carrer,Nom_carrer,Dia_mes,...,Nom_barri,Hora_dia,Número_expedient,Latitud_WGS84,Codi_barri,Mes_any,_id,Num_postal,Longitud_WGS84,Descripcio_dia_setmana
48,1,430686.858,2025,Manca d'atenció a la conducció,Ciutat Vella,Matí,4580920.057,86902,Nou de la Rambla,31,...,el Raval,11,2025S003058,41.37496791,1,5,49,,2.17000266,Dissabte
88,1,430951.604,2025,Manca precaució efectuar marxa enrera,Ciutat Vella,Matí,4580992.967,21306,Arc del Teatre,25,...,el Raval,9,2025S004990,41.37564736,1,8,89,63,2.17315996,Dilluns
15,1,430934.440,2025,Manca d'atenció a la conducció,Ciutat Vella,Matí,4580915.689,198804,Paral·lel,14,...,el Raval,8,2025S000848,41.37494986,1,2,16,36,2.17296353,Divendres
63,1,431292.130,2025,Desobeir semàfor,Ciutat Vella,Tarda,4580896.397,700025,Josep Carner,3,...,el Raval,17,2025S003871,41.37480675,1,7,64,27,2.17724269,Dijous
54,1,431113.444,2025,Manca d'atenció a la conducció,Ciutat Vella,Matí,4581084.290,140203,Drassanes,17,...,el Raval,11,2025S003540,41.37648376,1,6,55,6-8,2.17508475,Dimarts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,1,430506.270,2025,Canvi de carril sense precaució,Ciutat Vella,Nit,4582109.552,250904,Pelai,4,...,el Raval,4,2025S003878,41.38566575,1,7,66,,2.16770684,Divendres
11,1,431006.919,2025,No determinada,Ciutat Vella,Tarda,4581454.052,348907,Unió,31,...,el Raval,19,2025S000597,41.37980497,1,1,12,3-5,2.17376886,Divendres
42,1,431139.289,2025,Manca d'atenció a la conducció,Ciutat Vella,Nit,4581105.966,269200,Portal de Santa Madrona,3,...,el Raval,23,2025S002415,41.37668120,1,5,43,10,2.17539133,Dissabte
91,1,430626.853,2025,Manca d'atenció a la conducció,Ciutat Vella,Tarda,4582082.013,250904,Pelai,5,...,el Raval,17,2025S005230,41.38542814,1,9,92,56,2.16915207,Divendres
59,1,430818.359,2025,Manca precaució efectuar marxa enrera,Ciutat Vella,Matí,4581230.955,198258,Marquès de Barberà,27,...,el Raval,11,2025S003704,41.37777940,1,6,60,20-22,2.17153953,Divendres

In [40]:
#2 añadiendo 'limit' y el número deseado

# Importo la librería
import requests

url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search"

params = {
    "resource_id": data1['result']['resources'][0]['id'],
    "limit" : 100
}

response_id = requests.get(url, params=params)

data2 = response_id.json()

data2

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'resource_id': '796504f6-7602-41a7-82a9-d3bd47e68dee',
  'fields': [{'type': 'int4', 'id': '_id'},
   {'type': 'text', 'id': 'Número_expedient'},
   {'type': 'numeric', 'id': 'Codi_districte'},
   {'type': 'text', 'id': 'Nom_districte'},
   {'type': 'numeric', 'id': 'Codi_barri'},
   {'type': 'text', 'id': 'Nom_barri'},
   {'type': 'numeric', 'id': 'Codi_carrer'},
   {'type': 'text', 'id': 'Nom_carrer'},
   {'type': 'text', 'id': 'Num_postal'},
   {'type': 'text', 'id': 'Descripcio_dia_setmana'},
   {'type': 'numeric', 'id': 'Nk_Any'},
   {'type': 'numeric', 'id': 'Mes_any'},
   {'type': 'text', 'id': 'Nom_mes'},
   {'type': 'numeric', 'id': 'Dia_mes'},
   {'type': 'numeric', 'id': 'Hora_dia'},
   {'type': 'text', 'id': 'Descripcio_torn'},
   {'type': 'text', 'id': 'Causa conductor'},
   {'type': 'numeric', 'id': 'Coordenada_UTM_X_ED50'},
   {'type': 'numeric', 'id': 'Coordenada_UTM_Y_ED50'},
   {'type': 'numeric', 'id': 'Longitud_WGS84'},
   {'type': 'numeric', 'id': 'Latitud_WGS84'}],
  'records': [{'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430843.618',
    'Nk_Any': '2025',
    'Causa conductor': 'No respectar distàncies',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4580926.531',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '5',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '14',
    'Número_expedient': '2025S000065',
    'Latitud_WGS84': '41.37503971',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 1,
    'Num_postal': '48',
    'Longitud_WGS84': '2.17187632',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430453.561',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4581623.910',
    'Codi_carrer': '254803',
    'Nom_carrer': 'Peu de la Creu',
    'Dia_mes': '9',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '23',
    'Número_expedient': '2025S000133',
    'Latitud_WGS84': '41.38128717',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 2,
    'Num_postal': '',
    'Longitud_WGS84': '2.16713227',
    'Descripcio_dia_setmana': 'Dijous'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430453.561',
    'Nk_Any': '2025',
    'Causa conductor': 'No respectat pas de vianants',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4581623.910',
    'Codi_carrer': '254803',
    'Nom_carrer': 'Peu de la Creu',
    'Dia_mes': '9',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '23',
    'Número_expedient': '2025S000133',
    'Latitud_WGS84': '41.38128717',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 3,
    'Num_postal': '',
    'Longitud_WGS84': '2.16713227',
    'Descripcio_dia_setmana': 'Dijous'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431179.015',
    'Nk_Any': '2025',
    'Causa conductor': 'Manca precaució incorporació circulació',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4581196.729',
    'Codi_carrer': '34308',
    'Nom_carrer': 'Rambla',
    'Dia_mes': '10',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '13',
    'Número_expedient': '2025S000159',
    'Latitud_WGS84': '41.37750208',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 4,
    'Num_postal': '9',
    'Longitud_WGS84': '2.17585604',
    'Descripcio_dia_setmana': 'Divendres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430352.425',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4581614.925',
    'Codi_carrer': '368100',
    'Nom_carrer': 'Guifré',
    'Dia_mes': '15',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '16',
    'Número_expedient': '2025S000256',
    'Latitud_WGS84': '41.38119749',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 5,
    'Num_postal': '',
    'Longitud_WGS84': '2.16592388',
    'Descripcio_dia_setmana': 'Dimecres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431106.571',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4581001.166',
    'Codi_carrer': '269200',
    'Nom_carrer': 'Portal de Santa Madrona',
    'Dia_mes': '16',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '18',
    'Número_expedient': '2025S000301',
    'Latitud_WGS84': '41.37573449',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 6,
    'Num_postal': '',
    'Longitud_WGS84': '2.17501202',
    'Descripcio_dia_setmana': 'Dijous'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430731.601',
    'Nk_Any': '2025',
    'Causa conductor': '',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4580968.994',
    'Codi_carrer': '86902',
    'Nom_carrer': 'Nou de la Rambla',
    'Dia_mes': '19',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '0',
    'Número_expedient': '2025S000335',
    'Latitud_WGS84': '41.37541252',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 7,
    'Num_postal': '103',
    'Longitud_WGS84': '2.17053206',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430178.716',
    'Nk_Any': '2025',
    'Causa conductor': 'Avançament defectuós/improcedent',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4581781.979',
    'Codi_carrer': '296508',
    'Nom_carrer': 'Sant Antoni',
    'Dia_mes': '19',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '20',
    'Número_expedient': '2025S000344',
    'Latitud_WGS84': '41.38268702',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 8,
    'Num_postal': '66',
    'Longitud_WGS84': '2.16382736',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430972.098',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4581122.920',
    'Codi_carrer': '140203',
    'Nom_carrer': 'Drassanes',
    'Dia_mes': '20',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '6',
    'Número_expedient': '2025S000353',
    'Latitud_WGS84': '41.37681957',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 9,
    'Num_postal': '14',
    'Longitud_WGS84': '2.17339021',
    'Descripcio_dia_setmana': 'Dilluns'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430453.561',
    'Nk_Any': '2025',
    'Causa conductor': 'Manca precaució incorporació circulació',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4581623.910',
    'Codi_carrer': '167709',
    'Nom_carrer': 'Joaquín Costa',
    'Dia_mes': '29',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '0',
    'Número_expedient': '2025S000521',
    'Latitud_WGS84': '41.38128717',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 10,
    'Num_postal': '',
    'Longitud_WGS84': '2.16713227',
    'Descripcio_dia_setmana': 'Dimecres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430467.436',
    'Nk_Any': '2025',
    'Causa conductor': 'No respectat pas de vianants',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4581526.468',
    'Codi_carrer': '701215',
    'Nom_carrer': 'Maria Aurèlia Capmany',
    'Dia_mes': '29',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '10',
    'Número_expedient': '2025S000526',
    'Latitud_WGS84': '41.38041074',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 11,
    'Num_postal': '',
    'Longitud_WGS84': '2.16730938',
    'Descripcio_dia_setmana': 'Dimecres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431006.919',
    'Nk_Any': '2025',
    'Causa conductor': 'No determinada',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4581454.052',
    'Codi_carrer': '348907',
    'Nom_carrer': 'Unió',
    'Dia_mes': '31',
    'Nom_mes': 'Gener',
    'Nom_barri': 'el Raval',
    'Hora_dia': '19',
    'Número_expedient': '2025S000597',
    'Latitud_WGS84': '41.37980497',
    'Codi_barri': '1',
    'Mes_any': '1',
    '_id': 12,
    'Num_postal': '3-5',
    'Longitud_WGS84': '2.17376886',
    'Descripcio_dia_setmana': 'Divendres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430684.954',
    'Nk_Any': '2025',
    'Causa conductor': 'No respectar distàncies',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4582066.489',
    'Codi_carrer': '34308',
    'Nom_carrer': 'Rambla',
    'Dia_mes': '6',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '10',
    'Número_expedient': '2025S000693',
    'Latitud_WGS84': '41.38529332',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 13,
    'Num_postal': '135',
    'Longitud_WGS84': '2.16984868',
    'Descripcio_dia_setmana': 'Dijous'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430972.098',
    'Nk_Any': '2025',
    'Causa conductor': 'No determinada',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4581122.920',
    'Codi_carrer': '140203',
    'Nom_carrer': 'Drassanes',
    'Dia_mes': '7',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '22',
    'Número_expedient': '2025S000737',
    'Latitud_WGS84': '41.37681957',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 14,
    'Num_postal': '14',
    'Longitud_WGS84': '2.17339021',
    'Descripcio_dia_setmana': 'Divendres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430601.160',
    'Nk_Any': '2025',
    'Causa conductor': 'No determinada',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4581056.732',
    'Codi_carrer': '308505',
    'Nom_carrer': 'Sant Pau',
    'Dia_mes': '8',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '8',
    'Número_expedient': '2025S000742',
    'Latitud_WGS84': '41.37619151',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 15,
    'Num_postal': '99B-101',
    'Longitud_WGS84': '2.16896229',
    'Descripcio_dia_setmana': 'Dissabte'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430934.440',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4580915.689',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '14',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '8',
    'Número_expedient': '2025S000848',
    'Latitud_WGS84': '41.37494986',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 16,
    'Num_postal': '36',
    'Longitud_WGS84': '2.17296353',
    'Descripcio_dia_setmana': 'Divendres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430578.975',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4580942.337',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '16',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '21',
    'Número_expedient': '2025S000890',
    'Latitud_WGS84': '41.37515927',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 17,
    'Num_postal': '74',
    'Longitud_WGS84': '2.16871013',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431121.687',
    'Nk_Any': '2025',
    'Causa conductor': 'Canvi de carril sense precaució',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4580897.913',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '23',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '6',
    'Número_expedient': '2025S001009',
    'Latitud_WGS84': '41.37480582',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 18,
    'Num_postal': '26',
    'Longitud_WGS84': '2.17520450',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431214.128',
    'Nk_Any': '2025',
    'Causa conductor': 'Canvi de carril sense precaució',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4580892.358',
    'Codi_carrer': '701349',
    'Nom_carrer': 'Drassanes',
    'Dia_mes': '24',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '12',
    'Número_expedient': '2025S001019',
    'Latitud_WGS84': '41.37476369',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 19,
    'Num_postal': '0',
    'Longitud_WGS84': '2.17631046',
    'Descripcio_dia_setmana': 'Dilluns'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431302.276',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4580803.952',
    'Codi_carrer': '701497',
    'Nom_carrer': 'B-10 (Llobregat)',
    'Dia_mes': '27',
    'Nom_mes': 'Febrer',
    'Nom_barri': 'el Raval',
    'Hora_dia': '1',
    'Número_expedient': '2025S001082',
    'Latitud_WGS84': '41.37397498',
    'Codi_barri': '1',
    'Mes_any': '2',
    '_id': 20,
    'Num_postal': 'K110',
    'Longitud_WGS84': '2.17737449',
    'Descripcio_dia_setmana': 'Dijous'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430967.495',
    'Nk_Any': '2025',
    'Causa conductor': '',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4581570.069',
    'Codi_carrer': '34308',
    'Nom_carrer': 'Rambla',
    'Dia_mes': '5',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '11',
    'Número_expedient': '2025S001244',
    'Latitud_WGS84': '41.38084652',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 21,
    'Num_postal': '65',
    'Longitud_WGS84': '2.17328420',
    'Descripcio_dia_setmana': 'Dimecres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431302.276',
    'Nk_Any': '2025',
    'Causa conductor': 'Canvi de carril sense precaució',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4580803.952',
    'Codi_carrer': '701266',
    'Nom_carrer': 'Litoral (Llobregat)',
    'Dia_mes': '8',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '18',
    'Número_expedient': '2025S001327',
    'Latitud_WGS84': '41.37397498',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 22,
    'Num_postal': 'K110',
    'Longitud_WGS84': '2.17737449',
    'Descripcio_dia_setmana': 'Dissabte'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431303.956',
    'Nk_Any': '2025',
    'Causa conductor': 'Canvi de carril sense precaució',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4580950.667',
    'Codi_carrer': '700025',
    'Nom_carrer': 'Josep Carner',
    'Dia_mes': '10',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '8',
    'Número_expedient': '2025S001351',
    'Latitud_WGS84': '41.37529655',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 23,
    'Num_postal': '',
    'Longitud_WGS84': '2.17737794',
    'Descripcio_dia_setmana': 'Dilluns'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430686.858',
    'Nk_Any': '2025',
    'Causa conductor': 'Gir indegut o sense precaució',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4580920.057',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '14',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '19',
    'Número_expedient': '2025S001451',
    'Latitud_WGS84': '41.37496791',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 24,
    'Num_postal': '',
    'Longitud_WGS84': '2.17000266',
    'Descripcio_dia_setmana': 'Divendres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430686.858',
    'Nk_Any': '2025',
    'Causa conductor': 'No respectat pas de vianants',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Tarda',
    'Coordenada_UTM_Y_ED50': '4580920.057',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '14',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '19',
    'Número_expedient': '2025S001451',
    'Latitud_WGS84': '41.37496791',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 25,
    'Num_postal': '',
    'Longitud_WGS84': '2.17000266',
    'Descripcio_dia_setmana': 'Divendres'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431372.370',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4580879.471',
    'Codi_carrer': '701265',
    'Nom_carrer': 'Litoral (Besòs)',
    'Dia_mes': '22',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '5',
    'Número_expedient': '2025S001602',
    'Latitud_WGS84': '41.37466114',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 26,
    'Num_postal': 'K109',
    'Longitud_WGS84': '2.17820405',
    'Descripcio_dia_setmana': 'Dissabte'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '431121.687',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4580897.913',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '23',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '4',
    'Número_expedient': '2025S001617',
    'Latitud_WGS84': '41.37480582',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 27,
    'Num_postal': '24',
    'Longitud_WGS84': '2.17520450',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430934.440',
    'Nk_Any': '2025',
    'Causa conductor': 'No respectar distàncies',
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Matí',
    'Coordenada_UTM_Y_ED50': '4580915.689',
    'Codi_carrer': '198804',
    'Nom_carrer': 'Paral·lel',
    'Dia_mes': '23',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '13',
    'Número_expedient': '2025S001621',
    'Latitud_WGS84': '41.37494986',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 28,
    'Num_postal': '36',
    'Longitud_WGS84': '2.17296353',
    'Descripcio_dia_setmana': 'Diumenge'},
   {'Codi_districte': '1',
    'Coordenada_UTM_X_ED50': '430935.567',
    'Nk_Any': '2025',
    'Causa conductor': "Manca d'atenció a la conducció",
    'Nom_districte': 'Ciutat Vella',
    'Descripcio_torn': 'Nit',
    'Coordenada_UTM_Y_ED50': '4580960.647',
    'Codi_carrer': '39800',
    'Nom_carrer': 'Ramon Berenguer el Vell',
    'Dia_mes': '23',
    'Nom_mes': 'Març',
    'Nom_barri': 'el Raval',
    'Hora_dia': '22',
    'Número_expedient': '2025S001624',
    'Latitud_WGS84': '41.37535488',
    'Codi_barri': '1',
    'Mes_any': '3',
    '_id': 29,
    'Num_postal': '',
    'Longitud_WGS84': '2.17297188',
    'Descripcio_dia_setmana': 'Diumenge'},

4. Converteix els resultats a un DataFrame.

In [43]:
# voy a convertir en DataFrame la última celda (donde recupero 100 registros aleatorios)

import pandas as pd

df1 = pd.DataFrame(data2['result']['records'])

df1.sample(3)

,Codi_districte,Coordenada_UTM_X_ED50,Nk_Any,Causa conductor,Nom_districte,Descripcio_torn,Coordenada_UTM_Y_ED50,Codi_carrer,Nom_carrer,Dia_mes,...,Nom_barri,Hora_dia,Número_expedient,Latitud_WGS84,Codi_barri,Mes_any,_id,Num_postal,Longitud_WGS84,Descripcio_dia_setmana
84,1,431161.593,2025,No respectat pas de vianants,Ciutat Vella,Tarda,4581300.310,34308,Rambla,7,...,el Raval,18,2025S004838,41.37843351,1,8,84,,2.17563594,Dijous
33,1,430483.305,2025,Manca d'atenció a la conducció,Ciutat Vella,Matí,4581638.697,254803,Peu de la Creu,8,...,el Raval,12,2025S001964,41.38142292,1,4,34,11-17,2.16748626,Dimarts
36,1,431292.130,2025,Manca d'atenció a la conducció,Ciutat Vella,Tarda,4580896.397,700025,Josep Carner,17,...,el Raval,19,2025S002125,41.37480675,1,4,37,27,2.17724269,Dijous

5. Desa el DataFrame en un fitxer .csv.

In [44]:
df.to_csv("resultado_accidentes.csv")